services:
  db:
    image: postgres:17
    container_name: flipstyle_db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 30s        # Checa a cada meio minuto
      timeout: 10s         # Espera até 10s pela resposta antes de considerar falha
      retries: 3           # Só marca como morto se falhar 3 vezes seguidas (ou seja, 1min 30s de erro real)
      start_period: 20s
    networks:
      - flipstyle_network
  web:
    build: .
    container_name: flipstyle_app
    restart: always
    volumes:
      - .:/app
      - ./media:/app/media
      - staticfiles_volume:/app/staticfiles
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - flipstyle_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx@sha256:0d3b80406a13a767339fbe2f41406d6c7da727ab89cf8fae399e81f780f814d1
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    depends_on:
      web: # <--- Ajustado para o nome real do seu serviço ali em cima
        condition: service_started # Como o 'web' não tem healthcheck configurado, usamos service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles_volume:/app/staticfiles:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/app/media:ro
      - /var/www/certbot:/var/www/certbot:ro        # <-- ADICIONE ISSO (Desafio)
      - /etc/letsencrypt:/etc/letsencrypt:ro        # <-- ADICIONE ISSO (Certificados)
    networks: # <--- IMPORTANTE: Adicione a rede para o Nginx enxergar o Django
      - flipstyle_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  staticfiles_volume:

networks:
  flipstyle_network:
    driver: bridge