worker_processes auto; 

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    # Aumentamos a taxa base para 20 requisições por segundo
    limit_req_zone $binary_remote_addr zone=my_limit_zone:10m rate=20r/s;

    # SERVER HTTP (Porta 80) - Trata o desafio do Certbot e redireciona o resto para HTTPS
    server {
        listen 80;
        server_name flipstylecompany.com.br www.flipstylecompany.com.br;

        # Essencial para o Certbot validar sem derrubar o container
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redireciona todo o tráfego HTTP normal para HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # SERVER HTTPS (Porta 443) - Sua aplicação segura
    server {
        listen 443 ssl;
        server_name flipstylecompany.com.br www.flipstylecompany.com.br;

        ssl_certificate /etc/letsencrypt/live/flipstylecompany.com.br/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/flipstylecompany.com.br/privkey.pem;

        # BLACKLIST
        location ~* /(wp-admin|wp-login|wp-content|wp-includes|\.php|admin) {
            access_log off;
            return 444;     
        }

        client_max_body_size 10M;
        add_header X-Content-Type-Options "nosniff";

        location /static/ {
            alias /app/staticfiles/;
            access_log off;
        }

        location /media/ {
            alias /app/media/;
            access_log off;
        }

        location / {
            # Burst aumentado para 60 para aguentar todas as imagens da home
            limit_req zone=my_limit_zone burst=60 nodelay; 

            proxy_pass http://web:8000; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}