# Generated by Django 5.2 on 2026-06-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sizes',
            field=models.ManyToManyField(blank=True, help_text='Tamanhos permitidos para esta subcategoria', related_name='subcategories', to='products.size'),
        ),
    ]
