# Generated by Django 5.2 on 2026-06-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='sizes',
        ),
    ]
