# Generated by Django 5.2 on 2026-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_subcategory_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/'),
        ),
    ]
