# Generated by Django 5.2.15 on 2026-07-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_brand_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
